#
# VenusWRT — OUI front-end for NetShift (sing-box domain routing engine).
# Licensed under GPL-2.0.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=NetShift
APP_NAME:=netshift
APP_DEPENDS:=+netshift

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
