#
# VenusWRT — OUI front-end for the Venus split-router / DPI-bypass engine.
# Licensed under GPL-2.0 (Venus project).
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Venus
APP_NAME:=venus
APP_DEPENDS:=+venus

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
