#
# VenusWRT — OUI wireless app (radios + SSIDs).
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Wireless
APP_NAME:=wireless
APP_DEPENDS:=

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
